<?
if(!isset($_PAGE_ID)) {
    $PAGE_ID = 'home';
}


?>
<!DOCTYPE html>
<html>
    <head>
    <title>Ben Del Vacchio</title>

    <link rel="stylesheet" href="/css/default.css" type="text/css" />

</head>
<body class="page-<? echo $PAGE_ID; ?>">

<header>


</header>

    <nav>
        <ul>
            <li>Home</li>
            <li>Resume</li>
            <li>Portfolio</li>
            <li>Hobbies</li>
        </ul>
    </nav>